### ISSUE TITLE
V站的自动签到好像已经挂了

### ISSUE THREAD

**Issue by Drshu** [bonfy/qiandao#3]
错误返回如下：
```
22.54s$ python3 v2ex.py
Traceback (most recent call last):
  File "v2ex.py", line 37, in <module>
    qiandao_v2ex()
  File "v2ex.py", line 24, in qiandao_v2ex
    u, p = re.findall(r'class="sl" name="([0-9A-Za-z]{64})"', resp.text)
ValueError: not enough values to unpack (expected 2, got 0)

```
请更新，谢谢

**Comment by bonfy** [comment]
我看了下，没有挂，刚还领到铜币了

```
时间 	类型 	数额 	余额 	描述
2017-04-19 10:16:18 +08:00 	每日登录奖励 	22.0 	7959.48 	20170419 的每日登录奖励 22 铜币
```

请检查下自己的网络，感觉上resp.text 没取到或者有问题（可以print出来看看，'class="sl" name="“这段有没有）
都还没到用户名、密码这步。。。应该也不是密码中特殊字符问题

**Comment by Drshu** [comment]
问题已解决 网络问题 谢谢
